spring:
  application:
    name: VinaAcademy
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      maxRequestSize: 1GB
      enabled: true
      maxFileSize: 1GB
application:
  jwt:
    refreshToken:
      expiration: 2592000
    accessToken:
      expiration: 86400
  hmac:
    secret: ${HMAC_SECRET:super-secret-key-for-hmac}
  storage:
    uploadDir: ${UPLOAD_DIR:/vinaacademy/uploads}
    hlsOutputDir: ${HLS_OUTPUT_DIR:/vinaacademy/hls}
  video:
    maxSize: 1073741824
  url:
    frontend: ${FRONTEND_URL:http://localhost:3000}

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/x-mpegURL, text/plain
    min-response-size: 1024

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false